# Generated by Django 6.0.5 on 2026-05-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200),
        ),
    ]
