# Generated by Django 6.1 on 2026-08-19 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0004_alter_image_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="total_views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="image",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["-total_views"], name="images_imag_total_v_df67af_idx"
            ),
        ),
    ]
