# Generated by Django 6.0.6 on 2026-08-21 07:58

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0004_alter_image_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="search_vector",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.SearchVector(
                        "title", config="english", weight="A"
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "description", config="english", weight="B"
                    ),
                    django.contrib.postgres.search.SearchConfig("english"),
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="image_search_vector_gin"
            ),
        ),
    ]
