# Generated by Django 6.0.6 on 2026-08-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0007_image_search_vector_image_image_search_vector_gin"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="download_error",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
