# Generated by Django 6.0.6 on 2026-08-27 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0008_image_download_error"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["-created", "-id"]},
        ),
        migrations.RemoveIndex(
            model_name="image",
            name="images_imag_created_d57897_idx",
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["-created", "-id"], name="images_imag_created_2f5292_idx"
            ),
        ),
    ]
