# Generated by Django 6.0.6 on 2026-09-02 19:58

from django.db import migrations
from django.db.models import Count, OuterRef, Subquery


def recount_likes(apps, schema_editor):
    """Set every counter to the number of likes actually on record.

    The column is a copy of the like table kept for speed, and the two had
    drifted apart: deleting an account clears its likes by cascade, and a
    cascade sends no signal for the counter to hear. Pictures were left
    claiming likes nobody had given, and the ranking sorts by this column.

    From here on the leaving account takes its likes with it, so this is a
    one-off repair of what piled up before that.
    """
    Image = apps.get_model("images", "Image")
    images = Image.objects.using(schema_editor.connection.alias)

    # order_by() clears the model's default ordering, which would otherwise
    # join the GROUP BY and count each picture once per row of it.
    counted = (
        images.filter(pk=OuterRef("pk"))
        .order_by()
        .annotate(likes=Count("users_like"))
        .values("likes")[:1]
    )
    images.update(total_likes=Subquery(counted))


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0009_alter_image_options_and_more"),
    ]

    operations = [
        # No reverse: the numbers this replaces were wrong, and putting wrong
        # numbers back is not a state worth restoring.
        migrations.RunPython(recount_likes, migrations.RunPython.noop, elidable=True),
    ]
