# Generated by Django 6.0.3 on 2026-09-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0010_recount_image_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="total_comments",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
