[project]
name = "social-network"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.2",
    "django-environ>=0.13.0",
    "pillow>=12.1.1",
    "pytest>=9.0.2",
    "pytest-django>=4.12.0",
    "social-auth-app-django>=5.7.0",
    "psycopg2-binary>=2.9",
    "requests>=2.32.5",
    "django-debug-toolbar>=6.3.0",
    "redis>=7.4.0",
    "django-storages[s3]>=1.14.6",
    "boto3>=1.42.95",
    "gunicorn>=25.3.0",
    "sorl-thumbnail>=13.0.0",
    "celery>=5.6.3",
    "django-ratelimit>=4.1.0",
]

[project.optional-dependencies]
dev = [
    "pytest-cov>=7.1.0",
    "ruff>=0.6.0",
    "fakeredis>=2.0.0",
]

[tool.setuptools]
packages = []

[tool.ruff.lint.per-file-ignores]
"app/settings/*.py" = ["F403", "F405", "F401"]
