# Generated by Django 6.0.3 on 2026-09-17 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
        ("images", "0011_image_total_comments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                condition=models.Q(("removed_at__isnull", False)),
                fields=["id"],
                name="comment_hidden_ids",
            ),
        ),
    ]
