# Generated by Django 6.0.6 on 2026-08-19 17:18

from django.conf import settings
from django.db import migrations


def create_missing_profiles(apps, schema_editor):
    """Back-fill profiles for users created before the post_save signal existed
    (superusers from createsuperuser, accounts made in the admin)."""
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Profile = apps.get_model("account", "Profile")
    db_alias = schema_editor.connection.alias

    missing = User.objects.using(db_alias).filter(profile__isnull=True)
    Profile.objects.using(db_alias).bulk_create(
        [Profile(user=user) for user in missing],
        batch_size=1000,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_profile_following_alter_contact_user_from_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # No reverse: dropping the profiles again would destroy data that is
        # legitimately in use once this has run.
        migrations.RunPython(
            create_missing_profiles,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
