# Generated by Django 6.0.6 on 2026-08-21 07:13

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_profile_following_alter_contact_user_from_and_more"),
    ]

    operations = [
        TrigramExtension(),
    ]
