# Generated by Django 6.0.6 on 2026-08-19 18:03

from django.conf import settings
from django.db import migrations
from django.db.models import Count
from django.db.models.functions import Lower

# Partial: social logins may leave the address empty, and several blank strings
# must stay allowed. Case-insensitive: one person owns one address whatever
# case they type it in.
CREATE_INDEX = """
    CREATE UNIQUE INDEX auth_user_email_ci_uniq
    ON auth_user (LOWER(email))
    WHERE email <> '';
"""
DROP_INDEX = "DROP INDEX IF EXISTS auth_user_email_ci_uniq;"


def normalize_emails(apps, schema_editor):
    """Lower-case every stored address, then refuse to go on if that leaves two
    accounts sharing one — the index below would fail with an opaque error."""
    User = apps.get_model(settings.AUTH_USER_MODEL)
    db_alias = schema_editor.connection.alias

    User.objects.using(db_alias).exclude(email="").update(email=Lower("email"))

    duplicates = list(
        User.objects.using(db_alias)
        .exclude(email="")
        .values("email")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
        .values_list("email", flat=True)
    )
    if duplicates:
        raise RuntimeError(
            "These addresses belong to more than one account: "
            f"{', '.join(duplicates)}. Free them up, then run migrate again."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_create_missing_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # No reverse: the original casing is gone once lowered.
        migrations.RunPython(normalize_emails, migrations.RunPython.noop),
        migrations.RunSQL(sql=CREATE_INDEX, reverse_sql=DROP_INDEX),
    ]
