# Generated by Django 6.0.6 on 2026-08-19 18:03

from django.conf import settings
from django.db import migrations
from django.db.models import Count, F
from django.db.models.functions import Lower

INDEX_NAME = "auth_user_email_ci_uniq"


def create_email_index(apps, schema_editor):
    """Partial: social logins may leave the address empty, and several blank
    strings must stay allowed. Case-insensitive: one person owns one address
    whatever case they type it in."""
    table = apps.get_model(settings.AUTH_USER_MODEL)._meta.db_table
    quote = schema_editor.quote_name
    schema_editor.execute(
        f"CREATE UNIQUE INDEX {quote(INDEX_NAME)} ON {quote(table)} "
        "(LOWER(email)) WHERE email <> ''"
    )


def drop_email_index(apps, schema_editor):
    schema_editor.execute(
        f"DROP INDEX IF EXISTS {schema_editor.quote_name(INDEX_NAME)}"
    )


def normalize_emails(apps, schema_editor):
    """Lower-case the stored addresses, then refuse to go on if that leaves two
    accounts sharing one — the index below would fail with an opaque error."""
    User = apps.get_model(settings.AUTH_USER_MODEL)
    db_alias = schema_editor.connection.alias

    # Touch only the rows that actually differ: rewriting every row would lock
    # the whole table and leave a dead version of each one behind.
    User.objects.using(db_alias).exclude(email="").annotate(
        lowered=Lower("email")
    ).exclude(email=F("lowered")).update(email=Lower("email"))

    duplicates = list(
        User.objects.using(db_alias)
        .exclude(email="")
        .values("email")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
        .values_list("email", flat=True)
    )
    if duplicates:
        raise RuntimeError(
            "These addresses belong to more than one account: "
            f"{', '.join(duplicates)}. Free them up, then run migrate again."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_create_missing_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # No reverse: the original casing is gone once lowered. Elidable because
        # a squashed history starts from data the forms already lower-case.
        migrations.RunPython(
            normalize_emails, migrations.RunPython.noop, elidable=True
        ),
        migrations.RunPython(create_email_index, drop_email_index),
    ]
