# Generated by Django 6.0.6 on 2026-08-22 15:59

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_enforce_unique_email"),
    ]

    operations = [
        TrigramExtension(),
    ]
