# Generated by Django 6.0.6 on 2026-08-22 15:59

from django.conf import settings
from django.db import migrations

# Raw SQL because auth.User belongs to Django: its Meta.indexes is out of reach.
CREATE_INDEX = """
    CREATE INDEX IF NOT EXISTS auth_user_trigram_gin
    ON auth_user
    USING gin (username gin_trgm_ops, first_name gin_trgm_ops, last_name gin_trgm_ops)
"""

DROP_INDEX = "DROP INDEX IF EXISTS auth_user_trigram_gin"


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_enable_pg_trgm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(sql=CREATE_INDEX, reverse_sql=DROP_INDEX),
    ]
