# Generated by Django 6.0.6 on 2026-08-25 10:17

from django.conf import settings
from django.db import migrations
from django.db.models import Count
from django.db.models.functions import Lower

INDEX_NAME = "auth_user_username_ci_uniq"


def refuse_case_duplicates(apps, schema_editor):
    """Stop before the index does, with a message that says what to fix.

    Nothing is rewritten here, unlike the email migration: a username is shown
    on every page and used to sign in, so the stored casing has to stay.
    """
    User = apps.get_model(settings.AUTH_USER_MODEL)
    duplicates = list(
        User.objects.using(schema_editor.connection.alias)
        .annotate(lowered=Lower("username"))
        .values("lowered")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
        .values_list("lowered", flat=True)
    )
    if duplicates:
        raise RuntimeError(
            "These names are held by more than one account, ignoring case: "
            f"{', '.join(duplicates)}. Rename all but one, then run migrate again."
        )


def create_username_index(apps, schema_editor):
    """The form already refuses a name taken in any casing, but two requests can
    pass that check at once; only the database can settle the race. Every
    account has a username, so no partial condition is needed here."""
    table = apps.get_model(settings.AUTH_USER_MODEL)._meta.db_table
    quote = schema_editor.quote_name
    schema_editor.execute(
        f"CREATE UNIQUE INDEX {quote(INDEX_NAME)} ON {quote(table)} (LOWER(username))"
    )


def drop_username_index(apps, schema_editor):
    schema_editor.execute(
        f"DROP INDEX IF EXISTS {schema_editor.quote_name(INDEX_NAME)}"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_user_trigram_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(refuse_case_duplicates, migrations.RunPython.noop),
        migrations.RunPython(create_username_index, drop_username_index),
    ]
