# Generated by Django 6.0.6 on 2026-08-28 15:55

from django.db import migrations, models
from django.db.models import Count, Min


def drop_duplicate_contacts(apps, schema_editor):
    """Leave one row per pair, the earliest, so the constraint below can be
    created at all.

    Duplicates got in through the race the constraint closes: nothing tells
    them apart but the id, and the oldest one is the follow that was actually
    acted upon.
    """
    Contact = apps.get_model("account", "Contact")
    contacts = Contact.objects.using(schema_editor.connection.alias)

    # order_by() clears the model's default ordering: it would otherwise add
    # `created` to the GROUP BY and every row would come out as its own pair.
    duplicated_pairs = (
        contacts.values("user_from", "user_to")
        .annotate(kept=Min("id"), rows=Count("id"))
        .filter(rows__gt=1)
        .order_by()
    )
    for pair in duplicated_pairs:
        contacts.filter(user_from=pair["user_from"], user_to=pair["user_to"]).exclude(
            id=pair["kept"]
        ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_enforce_unique_username"),
    ]

    operations = [
        # No reverse: the removed rows were copies, and putting copies back is
        # not a state worth restoring. Elidable because a history squashed past
        # this point starts with the constraint already in place.
        migrations.RunPython(
            drop_duplicate_contacts, migrations.RunPython.noop, elidable=True
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("user_from", "user_to"), name="account_contact_from_to_uniq"
            ),
        ),
    ]
