# Generated by Django 6.1 on 2026-08-20 11:46

from django.db import migrations


def delete_orphaned_image_actions(apps, schema_editor):
    """
    Drop feed entries left behind by images that no longer exist.

    Action points at its target through a generic relation, so the database
    never cascaded these away. From now on the post_delete cleanup task keeps
    them in sync; this removes the ones that piled up before it existed.
    """
    Action = apps.get_model("actions", "Action")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Image = apps.get_model("images", "Image")

    image_ct = ContentType.objects.filter(app_label="images", model="image").first()
    if image_ct is None:
        return

    Action.objects.filter(target_ct=image_ct).exclude(
        target_id__in=Image.objects.values("id")
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("images", "0005_image_total_views_image_updated_and_more"),
    ]

    operations = [
        migrations.RunPython(
            delete_orphaned_image_actions,
            migrations.RunPython.noop,
        ),
    ]
