# Generated by Django 6.0.6 on 2026-08-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0002_delete_orphaned_image_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="verb",
            field=models.CharField(
                choices=[
                    ("has created an account", "Created Account"),
                    ("uploaded image", "Uploaded Image"),
                    ("bookmarked image", "Bookmarked Image"),
                    ("likes", "Liked Image"),
                    ("is following", "Followed User"),
                ],
                max_length=255,
            ),
        ),
    ]
