# Generated by Django 6.0.6 on 2026-08-26 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0003_alter_action_verb"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"ordering": ["-created", "-id"]},
        ),
        migrations.RemoveIndex(
            model_name="action",
            name="actions_act_created_64f10d_idx",
        ),
        migrations.RemoveIndex(
            model_name="action",
            name="actions_act_target__614ba0_idx",
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["-created", "-id"], name="actions_act_created_a01dcf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["target_ct", "target_id"], name="actions_act_target__f20513_idx"
            ),
        ),
    ]
