# Generated by Django 6.0.3 on 2026-09-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0004_alter_action_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="verb",
            field=models.CharField(
                choices=[
                    ("has created an account", "Created Account"),
                    ("uploaded image", "Uploaded Image"),
                    ("bookmarked image", "Bookmarked Image"),
                    ("likes", "Liked Image"),
                    ("commented on", "Commented Image"),
                    ("is following", "Followed User"),
                ],
                max_length=255,
            ),
        ),
    ]
